---
# This playbook deploys the whole application stack in this site.

- hosts: all
  sudo: yes
  roles:
    - common

#- name: configure and deploy the webservers and application code
#  hosts: webservers
#  remote_user: root

#  roles:
#    - web

- hosts: mysqlservers
  sudo: yes
  roles:
    - mysqlservers

- hosts: mongoservers
  sudo: yes
  roles:
    - mongoservers

- hosts: microservices
  sudo: yes
  roles:
    - microservices
