---
# This role will install microservices dependencies

- name: install microservices dependencies
  apt: name={{item}} state=present
  with_items:
    - golang
    - haproxy
    - supervisor

- name: create microservices groups
  group: name={{item.value.group}} state=present
  with_dict: "{{services}}"

- name: create microservices users
  user: name={{item.value.user}} group={{item.value.group}} state=present
  with_dict: "{{services}}"

- name: copy haproxy default file
  template:
    src=etc/default/haproxy.j2
    dest=/etc/default/haproxy

- name: copy haproxy configuration file
  template:
    src=etc/haproxy/haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

# @todo: config de supervisor + su notify restart y config de cada app
